In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import time
from datetime import datetime
import itertools
import gc
import pickle
from xgboost import XGBRegressor
from xgboost import plot_importance
from sklearn.decomposition import PCA

%matplotlib inline

In [5]:
data1 = pd.read_pickle('data2.pkl')

In [6]:
data1

,date_block_num,shop_id,item_id,ID,city_id,item_category_id,type_id,sub_id,item_cnt_month,shop_cnt_month,...,date_shop_avg_item_cnt,date_shop_avg_item_cnt_lag_1_x,date_shop_avg_item_cnt_lag_3,date_shop_avg_item_cnt_lag_6,date_shop_avg_item_cnt_lag_12,date_cat_avg_item_cnt,date_shop_cat_avg_item_cnt,date_city_avg_item_cnt,date_item_city_avg_item_cnt,date_shop_avg_item_cnt_lag_1_y
4478844,12,2,27,0,0,19,5,12,0.0,883.0,...,0.117004,0.151489,0.095398,0.096130,0.141724,0.752930,0.793945,0.117004,0.0,0.151489
4478847,12,2,32,0,0,40,11,6,1.0,883.0,...,0.117004,0.151489,0.095398,0.096130,0.141724,0.261230,0.041809,0.117004,1.0,0.151489
4478848,12,2,33,0,0,37,11,1,1.0,883.0,...,0.117004,0.151489,0.095398,0.096130,0.141724,0.194824,0.052246,0.117004,1.0,0.151489
4478864,12,2,53,0,0,57,13,10,0.0,883.0,...,0.117004,0.151489,0.095398,0.096130,0.141724,0.099365,0.004631,0.117004,0.0,0.151489
4478868,12,2,59,0,0,57,13,10,0.0,883.0,...,0.117004,0.151489,0.095398,0.096130,0.141724,0.099365,0.004631,0.117004,0.0,0.151489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11098650,34,45,3280,214190,20,55,13,4,0.0,0.0,...,0.000000,0.129761,0.139282,0.142334,0.185913,0.000000,0.000000,0.000000,0.0,0.129761
11098651,34,45,4393,214191,20,22,5,16,0.0,0.0,...,0.000000,0.129761,0.139282,0.142334,0.185913,0.000000,0.000000,0.000000,0.0,0.129761
11098652,34,45,4352,214192,20,22,5,16,0.0,0.0,...,0.000000,0.129761,0.139282,0.142334,0.185913,0.000000,0.000000,0.000000,0.0,0.129761
11098657,34,45,15757,214197,20,55,13,4,0.0,0.0,...,0.000000,0.129761,0.139282,0.142334,0.185913,0.000000,0.000000,0.000000,0.0,0.129761
11098659,34,45,969,214199,20,37,11,1,0.0,0.0,...,0.000000,0.129761,0.139282,0.142334,0.185913,0.000000,0.000000,0.000000,0.0,0.129761

In [7]:
from scipy.stats import chi2_contingency

In [8]:
q2_out=chi2_contingency(data1)

In [21]:
col = data1.columns

In [48]:
[data1.corr()[col[1]] > 0.4].sum()

AttributeError: 'list' object has no attribute 'sum'

In [40]:
x = []
for i in col:
    x.[append.data1.corr[i]>0.4].sum()

item_cnt_month                 1.000000
item_shop_cnt_month            1.000000
season_item_shop_avg_cnt       1.000000
season_sub_avg_cnt             0.563785
item_shop_cnt_month_lag_1      0.705400
item_shop_cnt_month_lag_3      0.623533
item_shop_cnt_month_lag_6      0.569603
date_item_avg_item_cnt         0.718269
date_cat_avg_item_cnt          0.563412
date_shop_cat_avg_item_cnt     0.670565
date_item_city_avg_item_cnt    0.889639
Name: item_shop_cnt_month, dtype: float64

In [24]:
f = pd.DataFrame([data1.shop_id,data1.item_id]).T

In [25]:
chi2_contingency(f)[1]

(140987835.91011295,
 0.0,
 1774864,
 array([[8.14774874e-02, 2.89185225e+01],
        [9.55253300e-02, 3.39044747e+01],
        [9.83348985e-02, 3.49016651e+01],
        ...,
        [1.23536728e+01, 4.38464633e+03],
        [4.43968019e+01, 1.57576032e+04],
        [2.84890249e+00, 1.01115110e+03]]))

In [32]:
b = []
for i in col:
    a = []
    for j in col:
        f = pd.DataFrame([data1[i],data1[j]]).T
        d = chi2_contingency(f)[1]
        a.append(d)
    b.append(a)
b

ValueError: The internally computed table of expected frequencies has a zero element at (0, 0).

In [35]:
b

[[1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  1.0,
  0.0,
  1.0],
 [0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0]]

In [ ]:
pd.DataFrame(b,columns = col, index = col)

In [14]:
pd.DataFrame(q2_out[3], columns = data1.columns)

,date_block_num,shop_id,item_id,ID,city_id,item_category_id,type_id,sub_id,item_cnt_month,shop_cnt_month,...,date_shop_avg_item_cnt,date_shop_avg_item_cnt_lag_1_x,date_shop_avg_item_cnt_lag_3,date_shop_avg_item_cnt_lag_6,date_shop_avg_item_cnt_lag_12,date_cat_avg_item_cnt,date_shop_cat_avg_item_cnt,date_city_avg_item_cnt,date_item_city_avg_item_cnt,date_shop_avg_item_cnt_lag_1_y
0,13.224437,18.825466,6681.657382,1990.493326,9.204378,26.409110,6.539585,9.888873,0.220251,1205.854196,...,0.191855,0.202740,0.203597,0.204074,0.203257,0.202403,0.235464,0.185835,0.212915,0.202740
1,25.536568,36.352233,12902.372041,3843.669911,17.773779,50.996355,12.628029,19.095550,0.425308,2328.520990,...,0.370475,0.391493,0.393148,0.394069,0.392491,0.390843,0.454684,0.358849,0.411141,0.391493
2,9.597049,13.661748,4848.916975,1444.512390,6.679669,19.165243,4.745814,7.176412,0.159837,875.095286,...,0.139230,0.147129,0.147751,0.148097,0.147505,0.146885,0.170878,0.134861,0.154513,0.147129
3,2.340669,3.332027,1182.624785,352.308807,1.629135,4.674300,1.157479,1.750288,0.038983,213.431036,...,0.033958,0.035884,0.036036,0.036120,0.035976,0.035825,0.041676,0.032892,0.037685,0.035884
4,2.316067,3.297006,1170.194766,348.605853,1.612012,4.625170,1.145313,1.731892,0.038574,211.187762,...,0.033601,0.035507,0.035657,0.035741,0.035597,0.035448,0.041238,0.032546,0.037289,0.035507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1774860,121.678889,173.214317,61478.357718,18314.656636,84.690067,242.991918,60.171142,90.988155,2.026543,11095.141724,...,1.765273,1.865422,1.873307,1.877694,1.870178,1.862325,2.166520,1.709876,1.959042,1.865422
1774861,123.233758,175.427729,62263.956475,18548.689750,85.772276,246.096980,60.940036,92.150844,2.052439,11236.920553,...,1.787830,1.889259,1.897245,1.901688,1.894076,1.886123,2.194205,1.731726,1.984075,1.889259
1774862,122.988084,175.078004,62139.829756,18511.711888,85.601284,245.606372,60.818549,91.967136,2.048347,11214.519116,...,1.784266,1.885492,1.893463,1.897897,1.890300,1.882363,2.189830,1.728273,1.980120,1.885492
1774863,128.592891,183.056650,64971.662925,19355.326683,89.502302,256.799133,63.590169,96.158257,2.141695,11725.586613,...,1.865579,1.971418,1.979752,1.984388,1.976445,1.968146,2.289625,1.807034,2.070358,1.971418
1774864,120.520414,171.565185,60893.037280,18140.287261,83.883754,240.678451,59.598267,90.121879,2.007249,10989.507588,...,1.748466,1.847661,1.855472,1.859817,1.852372,1.844595,2.145893,1.693597,1.940390,1.847661